# Generated by Django 2.2.6 on 2019-10-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Template Title')),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=300, verbose_name='Template Image Url')),
                ('color', models.CharField(max_length=10, verbose_name='Template Color')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="User's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=30, verbose_name='Review Title')),
                ('score', models.FloatField(verbose_name='Score')),
                ('comment', models.CharField(max_length=300, verbose_name='Review Comment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User')),
            ],
        ),
    ]
